-- ============================================================
-- CakeUz — Supabase schema (run once in SQL Editor)
-- All column names are snake_case; frontend adapter maps to camelCase.
-- RLS is left OFF for a single-user app; layer auth in a later round.
-- ============================================================

-- Wipe any previous run so the script is idempotent during setup.
drop table if exists activity_log    cascade;
drop table if exists shopping_items  cascade;
drop table if exists shopping_trips  cascade;
drop table if exists orders          cascade;
drop table if exists recipe_ingredients cascade;
drop table if exists recipes         cascade;
drop table if exists price_history   cascade;
drop table if exists ingredients     cascade;

-- ── INGREDIENTS ─────────────────────────────────────────────
create table ingredients (
  id     bigint generated by default as identity primary key,
  name   text   not null,
  stock  numeric not null default 0,
  unit   text   not null,
  cost   numeric not null default 0
);

-- ── PRICE HISTORY ───────────────────────────────────────────
create table price_history (
  id      bigint generated by default as identity primary key,
  ing_id  bigint not null references ingredients(id) on delete cascade,
  date    date   not null,
  cost    numeric not null
);
create index on price_history (ing_id);

-- ── RECIPES (with per-recipe batch cost defaults) ───────────
create table recipes (
  id                        bigint generated by default as identity primary key,
  name                      text not null,
  yield                     text,
  suggested_sell_price      numeric not null default 0,
  default_labour            numeric not null default 20,
  default_electricity       numeric not null default 5,
  default_packing_per_unit  numeric not null default 2
);

create table recipe_ingredients (
  id         bigint generated by default as identity primary key,
  recipe_id  bigint not null references recipes(id) on delete cascade,
  ing_id     bigint not null references ingredients(id) on delete cascade,
  qty        numeric not null,
  unit       text
);
create index on recipe_ingredients (recipe_id);

-- ── ORDERS ──────────────────────────────────────────────────
create table orders (
  id                   bigint generated by default as identity primary key,
  customer             text not null,
  customer_phone       text,
  customer_email       text,
  customer_address     text,
  recipe_id            bigint references recipes(id) on delete set null,
  qty                  integer not null default 1,
  note                 text,
  due_date             date,
  status               text not null default 'pending',
  -- Pre-filled from the recipe, editable per order:
  sell_price_per_unit  numeric,
  labour               numeric,
  electricity          numeric,
  packing_per_unit     numeric,
  -- Pass-through to customer, NOT part of cake margin:
  transport_cost       numeric not null default 0,
  -- Snapshots computed at save time:
  ingredient_cost      numeric not null default 0,
  cake_cost            numeric not null default 0,
  ingredient_snapshot  jsonb,
  -- Lifecycle:
  completed_date       date,
  created_at           timestamptz not null default now()
);
create index on orders (status, due_date);

-- ── SHOPPING ────────────────────────────────────────────────
create table shopping_trips (
  id           bigint generated by default as identity primary key,
  date         date not null,
  shop         text,
  total        numeric not null default 0,
  receipt_img  text
);

create table shopping_items (
  id          bigint generated by default as identity primary key,
  trip_id     bigint not null references shopping_trips(id) on delete cascade,
  ing_id      bigint not null references ingredients(id) on delete cascade,
  qty         numeric not null,
  unit_price  numeric not null
);
create index on shopping_items (trip_id);

-- ── ACTIVITY LOG (structured before/after for audit) ────────
create table activity_log (
  id             bigint generated by default as identity primary key,
  type           text,
  action         text,
  detail         text,
  entity_type    text,         -- 'ingredient' | 'recipe' | 'order' | 'trip' | null
  entity_id      bigint,
  field_changes  jsonb,        -- {"cost": {"old": 2.35, "new": 2.50}, ...}
  time           timestamptz not null default now()
);
create index on activity_log (entity_type, entity_id);
create index on activity_log (time desc);

-- ── SECURITY ────────────────────────────────────────────────
-- Single-user app; the anon key has full read+write.
-- RLS is left disabled. Add policies later if multi-user is needed.
alter table ingredients          disable row level security;
alter table price_history        disable row level security;
alter table recipes              disable row level security;
alter table recipe_ingredients   disable row level security;
alter table orders               disable row level security;
alter table shopping_trips       disable row level security;
alter table shopping_items       disable row level security;
alter table activity_log         disable row level security;
